# Generated by Django 5.1.3 on 2025-12-21 06:50

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='blocks',
            field=models.JSONField(blank=True, default=list, help_text='Block-based content as JSON array'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Legacy: Lesson content in Markdown (use blocks instead)'),
        ),
    ]
