# Generated by Django 5.1.3 on 2025-12-22 01:56

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_allow_blank_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='long_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Detailed course overview - explains modules, structure, prerequisites'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Short course description for cards and listings'),
        ),
    ]
