# Generated by Django 5.1.3 on 2025-12-22 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)', max_length=500),
        ),
        migrations.CreateModel(
            name='BunnyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(help_text='Bunny Stream video GUID', max_length=36, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='bunny_video',
            field=models.ForeignKey(blank=True, help_text='Bunny Stream video (takes precedence over video_url)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.bunnyvideo'),
        ),
    ]
