# Generated by Django 5.1.3 on 2025-12-22 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_focus_keyword'),
        ('courses', '0006_alter_lesson_video_url_bunnyvideo_lesson_bunny_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Difficulty level (optional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of learning objectives (optional)'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorization (optional)', related_name='courses', to='blog.tag'),
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforcement', models.CharField(choices=[('recommended', 'Recommended'), ('required', 'Required')], default='recommended', help_text='Whether the prerequisite is recommended or required', max_length=20)),
                ('course', models.ForeignKey(help_text='The course that has prerequisites', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.course')),
                ('required_course', models.ForeignKey(help_text='The course that must be completed first', on_delete=django.db.models.deletion.CASCADE, related_name='is_prerequisite_for', to='courses.course')),
            ],
            options={
                'ordering': ['enforcement', 'required_course__title'],
                'unique_together': {('course', 'required_course')},
            },
        ),
    ]
