# Generated by Django 5.1.3 on 2025-12-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_course_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunnyvideo',
            name='thumbnail_blurhash',
            field=models.CharField(blank=True, help_text='Blurhash placeholder for thumbnail', max_length=100),
        ),
    ]
