/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsrTestRouteImport } from './routes/ssr-test'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as CoursesDashboardRouteImport } from './routes/courses.dashboard'
import { Route as BlogNewRouteImport } from './routes/blog.new'
import { Route as BlogDashboardRouteImport } from './routes/blog.dashboard'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCoursesRouteImport } from './routes/app.courses'
import { Route as CoursesSlugIndexRouteImport } from './routes/courses.$slug.index'
import { Route as CoursesSlugLessonSlugRouteImport } from './routes/courses.$slug.$lessonSlug'
import { Route as BlogTagSlugRouteImport } from './routes/blog.tag.$slug'
import { Route as BlogEditSlugRouteImport } from './routes/blog.edit.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'
import { Route as AppCoursesSlugRouteImport } from './routes/app.courses.$slug'
import { Route as AppCoursesSlugLessonSlugRouteImport } from './routes/app.courses.$slug.$lessonSlug'

const SsrTestRoute = SsrTestRouteImport.update({
  id: '/ssr-test',
  path: '/ssr-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesDashboardRoute = CoursesDashboardRouteImport.update({
  id: '/courses/dashboard',
  path: '/courses/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNewRoute = BlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDashboardRoute = BlogDashboardRouteImport.update({
  id: '/blog/dashboard',
  path: '/blog/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const CoursesSlugIndexRoute = CoursesSlugIndexRouteImport.update({
  id: '/courses/$slug/',
  path: '/courses/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugLessonSlugRoute = CoursesSlugLessonSlugRouteImport.update({
  id: '/courses/$slug/$lessonSlug',
  path: '/courses/$slug/$lessonSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/blog/tag/$slug',
  path: '/blog/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEditSlugRoute = BlogEditSlugRouteImport.update({
  id: '/blog/edit/$slug',
  path: '/blog/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesSlugRoute = AppCoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppCoursesSlugLessonSlugRoute =
  AppCoursesSlugLessonSlugRouteImport.update({
    id: '/$lessonSlug',
    path: '/$lessonSlug',
    getParentRoute: () => AppCoursesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/ssr-test': typeof SsrTestRoute
  '/app/courses': typeof AppCoursesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/dashboard': typeof BlogDashboardRoute
  '/blog/new': typeof BlogNewRoute
  '/courses/dashboard': typeof CoursesDashboardRoute
  '/store/$slug': typeof StoreSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/store': typeof StoreIndexRoute
  '/app/courses/$slug': typeof AppCoursesSlugRouteWithChildren
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/edit/$slug': typeof BlogEditSlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/courses/$slug/$lessonSlug': typeof CoursesSlugLessonSlugRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
  '/app/courses/$slug/$lessonSlug': typeof AppCoursesSlugLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/ssr-test': typeof SsrTestRoute
  '/app/courses': typeof AppCoursesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/dashboard': typeof BlogDashboardRoute
  '/blog/new': typeof BlogNewRoute
  '/courses/dashboard': typeof CoursesDashboardRoute
  '/store/$slug': typeof StoreSlugRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/store': typeof StoreIndexRoute
  '/app/courses/$slug': typeof AppCoursesSlugRouteWithChildren
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/edit/$slug': typeof BlogEditSlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/courses/$slug/$lessonSlug': typeof CoursesSlugLessonSlugRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
  '/app/courses/$slug/$lessonSlug': typeof AppCoursesSlugLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/ssr-test': typeof SsrTestRoute
  '/app/courses': typeof AppCoursesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/dashboard': typeof BlogDashboardRoute
  '/blog/new': typeof BlogNewRoute
  '/courses/dashboard': typeof CoursesDashboardRoute
  '/store/$slug': typeof StoreSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/store/': typeof StoreIndexRoute
  '/app/courses/$slug': typeof AppCoursesSlugRouteWithChildren
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/edit/$slug': typeof BlogEditSlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/courses/$slug/$lessonSlug': typeof CoursesSlugLessonSlugRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/app/courses/$slug/$lessonSlug': typeof AppCoursesSlugLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/logout'
    | '/signup'
    | '/ssr-test'
    | '/app/courses'
    | '/app/dashboard'
    | '/app/settings'
    | '/blog/$slug'
    | '/blog/dashboard'
    | '/blog/new'
    | '/courses/dashboard'
    | '/store/$slug'
    | '/app/'
    | '/blog'
    | '/store'
    | '/app/courses/$slug'
    | '/blog/category/$slug'
    | '/blog/edit/$slug'
    | '/blog/tag/$slug'
    | '/courses/$slug/$lessonSlug'
    | '/courses/$slug'
    | '/app/courses/$slug/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/logout'
    | '/signup'
    | '/ssr-test'
    | '/app/courses'
    | '/app/dashboard'
    | '/app/settings'
    | '/blog/$slug'
    | '/blog/dashboard'
    | '/blog/new'
    | '/courses/dashboard'
    | '/store/$slug'
    | '/app'
    | '/blog'
    | '/store'
    | '/app/courses/$slug'
    | '/blog/category/$slug'
    | '/blog/edit/$slug'
    | '/blog/tag/$slug'
    | '/courses/$slug/$lessonSlug'
    | '/courses/$slug'
    | '/app/courses/$slug/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/logout'
    | '/signup'
    | '/ssr-test'
    | '/app/courses'
    | '/app/dashboard'
    | '/app/settings'
    | '/blog/$slug'
    | '/blog/dashboard'
    | '/blog/new'
    | '/courses/dashboard'
    | '/store/$slug'
    | '/app/'
    | '/blog/'
    | '/store/'
    | '/app/courses/$slug'
    | '/blog/category/$slug'
    | '/blog/edit/$slug'
    | '/blog/tag/$slug'
    | '/courses/$slug/$lessonSlug'
    | '/courses/$slug/'
    | '/app/courses/$slug/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  SsrTestRoute: typeof SsrTestRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogDashboardRoute: typeof BlogDashboardRoute
  BlogNewRoute: typeof BlogNewRoute
  CoursesDashboardRoute: typeof CoursesDashboardRoute
  StoreSlugRoute: typeof StoreSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogEditSlugRoute: typeof BlogEditSlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
  CoursesSlugLessonSlugRoute: typeof CoursesSlugLessonSlugRoute
  CoursesSlugIndexRoute: typeof CoursesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ssr-test': {
      id: '/ssr-test'
      path: '/ssr-test'
      fullPath: '/ssr-test'
      preLoaderRoute: typeof SsrTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/dashboard': {
      id: '/courses/dashboard'
      path: '/courses/dashboard'
      fullPath: '/courses/dashboard'
      preLoaderRoute: typeof CoursesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/new': {
      id: '/blog/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof BlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/dashboard': {
      id: '/blog/dashboard'
      path: '/blog/dashboard'
      fullPath: '/blog/dashboard'
      preLoaderRoute: typeof BlogDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses': {
      id: '/app/courses'
      path: '/courses'
      fullPath: '/app/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/courses/$slug/': {
      id: '/courses/$slug/'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug/$lessonSlug': {
      id: '/courses/$slug/$lessonSlug'
      path: '/courses/$slug/$lessonSlug'
      fullPath: '/courses/$slug/$lessonSlug'
      preLoaderRoute: typeof CoursesSlugLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$slug': {
      id: '/blog/tag/$slug'
      path: '/blog/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/edit/$slug': {
      id: '/blog/edit/$slug'
      path: '/blog/edit/$slug'
      fullPath: '/blog/edit/$slug'
      preLoaderRoute: typeof BlogEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/courses/$slug': {
      id: '/app/courses/$slug'
      path: '/$slug'
      fullPath: '/app/courses/$slug'
      preLoaderRoute: typeof AppCoursesSlugRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/app/courses/$slug/$lessonSlug': {
      id: '/app/courses/$slug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/app/courses/$slug/$lessonSlug'
      preLoaderRoute: typeof AppCoursesSlugLessonSlugRouteImport
      parentRoute: typeof AppCoursesSlugRoute
    }
  }
}

interface AppCoursesSlugRouteChildren {
  AppCoursesSlugLessonSlugRoute: typeof AppCoursesSlugLessonSlugRoute
}

const AppCoursesSlugRouteChildren: AppCoursesSlugRouteChildren = {
  AppCoursesSlugLessonSlugRoute: AppCoursesSlugLessonSlugRoute,
}

const AppCoursesSlugRouteWithChildren = AppCoursesSlugRoute._addFileChildren(
  AppCoursesSlugRouteChildren,
)

interface AppCoursesRouteChildren {
  AppCoursesSlugRoute: typeof AppCoursesSlugRouteWithChildren
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesSlugRoute: AppCoursesSlugRouteWithChildren,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppRouteChildren {
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  SsrTestRoute: SsrTestRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogDashboardRoute: BlogDashboardRoute,
  BlogNewRoute: BlogNewRoute,
  CoursesDashboardRoute: CoursesDashboardRoute,
  StoreSlugRoute: StoreSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogEditSlugRoute: BlogEditSlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
  CoursesSlugLessonSlugRoute: CoursesSlugLessonSlugRoute,
  CoursesSlugIndexRoute: CoursesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
